version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
  web:
    build: .
    command: >
      bash -c '
      python manage.py makemigrations service
      &&
      python manage.py migrate
      &&
      python manage.py createsuperuserwithpassword --username toren332 --password mypass321 --email ttt@ttt.ttt --preserve
      &&
      python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
