# Generated by Django 2.2.4 on 2019-08-20 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_photo', models.ImageField(upload_to='original/')),
                ('edited_photo', models.ImageField(upload_to='edited/')),
            ],
        ),
        migrations.CreateModel(
            name='FaceBorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('w', models.PositiveIntegerField()),
                ('h', models.PositiveIntegerField()),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Obj')),
            ],
        ),
    ]
